from enum import (
    Enum,
    auto,
)


class AILabConfig(Enum):
    aws_access_key_id = auto()
    aws_region = auto()
    aws_secret_access_key = auto()
    bfs_bucket = auto()
    bfs_encryption = auto()
    bfs_host_name = auto()
    bfs_internal_host_name = auto()
    bfs_internal_port = auto()
    bfs_password = auto()
    bfs_port = auto()
    bfs_service = auto()
    bfs_user = auto()
    cert_vld = auto()
    client_cert = auto()
    client_key = auto()
    db_encryption = auto()
    db_host_name = auto()
    db_password = auto()
    db_port = auto()
    db_schema = auto()
    db_user = auto()
    disk_size = auto()
    huggingface_token = auto()
    itde_container = auto()
    itde_network = auto()
    itde_volume = auto()
    mem_size = auto()
    saas_account_id = auto()
    saas_database_id = auto()
    saas_database_name = auto()
    saas_token = auto()
    saas_url = auto()
    slc_alias = auto()
    slc_flavor_cuda = auto()
    slc_flavor_non_cuda = auto()
    slc_source = auto()
    slc_target_dir = auto()
    sme_aws_bucket = auto()
    sme_aws_connection = auto()
    sme_aws_role = auto()
    storage_backend = auto()
    te_bfs_connection = auto()
    te_hf_connection = auto()
    te_models_bfs_dir = auto()
    te_models_cache_dir = auto()
    text_ai_pre_release_url = auto()
    text_ai_zip_password = auto()
    trusted_ca = auto()
    txaie_bfs_connection = auto()
    txaie_models_bfs_dir = auto()
    txaie_models_cache_dir = auto()
    txaie_slc_file_local_path = auto()
    use_itde = auto()


class StorageBackend(Enum):
    onprem = auto()
    saas = auto()
