from enum import Enum


class AILabConfig(Enum):
    use_itde = "USE_ITDE"
    db_host_name = "EXTERNAL_HOST_NAME"
    db_port = "DB_PORT"
    db_schema = "SCHEMA"
    db_user = "USER"
    db_password = "PASSWORD"
    db_encryption = "ENCRYPTION"
    cert_vld = "CERTIFICATE_VALIDATION"
    trusted_ca = "TRUSTED_CA"
    client_cert = "CLIENT_CERTIFICATE"
    client_key = "PRIVATE_KEY"
    bfs_host_name = "BUCKETFS_HOST_NAME"
    bfs_port = "BUCKETFS_PORT"
    bfs_service = "BUCKETFS_SERVICE"
    bfs_bucket = "BUCKETFS_BUCKET"
    bfs_user = "BUCKETFS_USER"
    bfs_password = "BUCKETFS_PASSWORD"
    bfs_encryption = "BUCKETFS_ENCRYPTION"
    mem_size = "MEMORY_SIZE"
    disk_size = "DISK_SIZE"
    huggingface_token = "HF_TOKEN"
    aws_bucket = "AWS_BUCKET"
    aws_region = "AWS_REGION"
    aws_access_key_id = "AWS_ACCESS_KEY_ID"
    aws_secret_access_key = "AWS_SECRET_ACCESS_KEY"
    itde_container = "ITDE_CONTAINER_NAME"
    itde_volume = "ITDE_VOLUME_NAME"
    itde_network = "ITDE_NETWORK_NAME"
    te_bfs_connection = "TE_BFS_CONN"
    te_models_bfs_dir = "TE_MODELS_BFS_DIR"
    te_hf_connection = "TE_TOKEN_CONN"
    te_models_cache_dir = "TE_MODELS_CACHE_DIR"
    sme_aws_connection = "SME_AWS_CONN"

