# This file can be replaced as soon as the following ticket is implemented:
# https://github.com/exasol/python-toolbox/issues/893

name: CI (optional)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  approve-optional-notebook-tests:
    name: Run Optional Notebook Tests?
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    environment: approve-optional-notebook-tests
    steps:
      - name: Detect Running Optional Notebook Tests
        run: true

  run-optional-notebook-tests:
    name: Optional Notebook Tests
    experimental
    needs:
      - approve-optional-notebook-tests
    uses: ./.github/workflows/tests-notebooks.yml
    with:
      selector: optional
    secrets: inherit
    permissions:
      contents: read
