name: CI

on:
  push:
    branches-ignore:
      - "main"

jobs:
  tests-job:
    name: Tests (Python-${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
          cache-dependency-path: poetry.lock
      - uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.2.2

      - name: Install Project
        run: poetry install

      - name: Run Tests
        run: poetry run pytest tests
