name: CI Build

on:
  push:
    branches-ignore:
      - "main"

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - name: Setup Python & Poetry Environment
       uses: ./.github/actions/prepare_poetry_env

     - name: Run pytest
       run: poetry run pytest
