name: CI Build

on:
  push:
    branches-ignore:
      - "main"

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0
     - name: Setup Python & Poetry Environment
       uses: ./.github/actions/prepare_poetry_env

     - name: Run pytest
       run: poetry run pytest
