name: Notebook Tests

on:
  workflow_call:
    input:
      selector:
        description: Selector which tests to include, e.g. notebooks-generic
        required: true
        type: string

jobs:

  fetch-notebook-tests:
    runs-on: ubuntu-24.04
    name: Creating test matrix for selector "${{ inputs.selector }}"
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v8
        with:
          poetry-version: "2.3.0"

      - id: matrix
        run: |
          JOBS=$(poetry run -- nox -s get-notebook-tests -- ${{ inputs.selector }})
          # JOBS=$(jq -cn '[
          #   {label: "N1", "file": "test_n1.py", backend: "onprem", runner: "ubuntu-24.04", pytest_params: "", require_success: true },
          #   {label: "N2", "file": "test_n2.py", backend: "onprem", runner: "ubuntu-22.04", pytest_params: "", require_success: false }
          #   ]'
          # )
          echo "jobs=$JOBS" >> "$GITHUB_OUTPUT"

    outputs:
      jobs: ${{ steps.matrix.outputs.jobs }}

  notebook-tests:
    name: ${{ matrix.el.label }} (${{ matrix.el.backend }})
    needs: fetch-notebook-tests
    runs-on: ${{ matrix.el.runner }}
    permissions:
      contents: read
    continue-on-error: ${{ ! matrix.el.require_success }}
    strategy:
      fail-fast: false
      matrix:
        el: ${{ fromJson(needs.fetch-notebook-tests.outputs.jobs) }}
    steps:
      - id: test
        name: Run Pytest
        run: |
          echo --backend=${{ matrix.el.backend }} \
            ${{ matrix.el.pytest_params }} \
            test/notebooks/${{ matrix.el.file }}
          # if: ${{ matrix.require_success && steps.test.outcome != 'success' }}
          if [ "${{ matrix.el.require_success }}" != true ]; then
            echo simulating test failure
            exit 1
          fi

      - name: Save Result
        if: always()
        run: |
          mkdir -p results
          jq -n '{
            file: "${{ matrix.el.file }}",
            require_success: ${{ matrix.el.require_success }},
            backend: "${{ matrix.el.backend }}",
            runner: "${{ matrix.el.runner }}",
            outcome: "${{ steps.test.outcome }}"
          }' > results/${{ matrix.el.file }}.json

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-result-${{ matrix.el.file }}
          path: results/${{ matrix.el.file }}.json

  evaluate-tests:
    name: Evaluate Test Results
    runs-on: ubuntu-24.04
    if: always()
    needs: notebook-tests
    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v8
        with:
          pattern: test-result-*
          path: results
          merge-multiple: true

      - name: Verify Success of Mandatory Tests
        run: |
          FAILURES=$(
            jq -s '[
              .[] | select(.require_success and .outcome != "success")
            ] ' results/*.json)
          COUNT=$(echo "$FAILURES" | jq length)

          if [ "$COUNT" -gt 0 ]; then
            echo "$COUNT mandatory tests have failed:"
            echo "$FAILURES" | jq .
            exit 1
          fi
