name: Notebook Tests

on:
  workflow_call:
    inputs:
      status-filter:
        description: 'Only nb tests with the given status will be executed (stable or unstable).'
        required: true
        type: string
      test-classification:
        description: 'Test classification: normal, large or gpu'
        required: true
        type: string

jobs:

  fetch-notebook-tests:
    runs-on: ubuntu-24.04
    name: Creating test matrix for selector "selector"
    steps:
      - id: matrix
        run: |
          TESTS=$(
            echo -n '['
            echo -n '{"label": "N1", "file": "test_n1.py", "backend": "onprem", "require_success": true }, '
            echo -n '{"label": "N2", "file": "test_n2.py", "backend": "onprem", "require_success": false }'
            echo -n ']'
          )
          echo "tests=$TESTS" >> "$GITHUB_OUTPUT"

    outputs:
      runner: "ubuntu-24.04"
      pytest_params: "x"
      tests: ${{ steps.matrix.outputs.tests }}

  notebook-tests:
    name: XXX ${{ matrix.nb_test.label }} (${{ matrix.nb_test.backend }})
    needs: fetch-notebook-tests
    runs-on: ${{ needs.fetch-notebook-tests.outputs.runner }}
    permissions:
      contents: read
    continue-on-error: ${{ inputs.status-filter == 'unstable' }}
    strategy:
      fail-fast: false
      matrix:
        nb_test: ${{ fromJson(needs.fetch-notebook-tests.outputs.tests) }}
    steps:
      - name: Sample
        run: echo --backend=${{ matrix.nb_test.backend }} \
            ${{ needs.fetch-notebook-tests.outputs.pytest_params }} \
            test/notebooks/${{ matrix.nb_test.file }}

      - id: test
        name: Simulate pytest failure
        if: ${{ ! matrix.nb_test.require_success }}
        run: |
          echo simulating test failure
          exit 1

      - name: Save result
        if: always()
        run: |
          mkdir -p results
          jq -n \
            --arg notebook "${{ matrix.nb_test.file }}" \
            --arg require_success "${{ matrix.nb_test.require_success }}" \
            --arg outcome "${{ steps.test.outcome }}" \
            '{
              notebook: $notebook,
              require_success: $require_success,
              outcome: $outcome
            }' \
            > results/${{ matrix.nbtest.file }}.json
