# Manual extension to merge-gate, not maintained by the exasol-toolbox.

name: Merge-Gate

on:
  workflow_call:

jobs:

  performance-checks:
    name: Performance
    uses: ./.github/workflows/performance-checks.yml
    permissions:

