name: Merge-Gate

on:
  workflow_call:

jobs:
  run-fast-checks:
    name: Fast Checks
    uses: ./.github/workflows/checks.yml
    permissions:
      contents: read

  approve-run-slow-tests:
    name: Approve Running Slow Tests?
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    # Configure this environment with required reviewers in GitHub settings.
    environment: approve-slow-test-execution
    steps:
      - name: Tests
        run: echo "Slow tests approved"

  run-slow-checks:
    name: Slow Checks
    needs:
      - approve-run-slow-tests
    uses: ./.github/workflows/slow-checks.yml
    secrets: inherit
    permissions:
      contents: read

  optional-slow-checks:
    name: Optional Slow
    needs:
      - approve-run-slow-tests
    uses: ./.github/workflows/tests-saas.yml
    secrets: inherit
    permissions:
      contents: read

  performance-checks:
    name: Performance
    uses: ./.github/workflows/performance-checks.yml
    permissions:
      contents: read

  approve-notebook-tests:
    name: Run Jupyter Notebook Tests?
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    # Configure this environment with required reviewers in GitHub settings.
    environment: approve-test-execution
    steps:
      - name: Detect Running Notebook Tests
        run: true

  run-stable-notebook-tests:
    name: Notebook Tests (stable)
    needs:
      - approve-notebook-tests
    uses: ./.github/workflows/tests-notebooks.yml
    secrets: inherit
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        class: [normal, large]
    with:
      status-filter: stable
      test-classification: ${{ matrix.class }}

  run-unstable-notebook-tests:
    name: Notebook Tests (unstable)
    needs:
      - approve-notebook-tests
    uses: ./.github/workflows/tests-notebooks.yml
    secrets: inherit
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        class: [normal, large]
    with:
      status-filter: unstable
      test-classification: ${{ matrix.class }}

  approve-gpu-notebook-tests:
    name: Run Jupyter GPU Notebook Tests?
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    # Configure this environment with required reviewers in GitHub settings.
    environment: approve-gpu-test-execution
    steps:
      - name: Detect Running GPU Notebook Tests
        run: true

  run-stable-gpu-notebook-tests:
    name: Notebook Tests GPU (stable)
    needs:
      - approve-gpu-notebook-tests
    uses: ./.github/workflows/tests-notebooks.yml
    secrets: inherit
    permissions:
      contents: read
    with:
      status-filter: stable
      test-classification: gpu

  # This job ensures inputs have been executed successfully.
  allow-merge:
    name: Allow Merge
    if: ${{ !cancelled() }}
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    needs:
      - run-fast-checks
      - run-slow-checks
      - optional-slow-checks
      - performance-checks
      - run-stable-notebook-tests
      - run-unstable-notebook-tests
      - run-stable-gpu-notebook-tests
    steps:
      - name: Branch Protection - failure if any ancestor failed
        if: ${{ needs.run-fast-checks.result == 'failure' || needs.run-slow-checks.result == 'failure' || needs.run-stable-notebook-tests.result == 'failure' || needs.run-stable-gpu-notebook-tests.result == 'failure' }}
        run: |
          echo '${{ toJSON(needs) }}'
          exit 1
      - name: Approve
        run: echo "Merge Approved"
