# Manual extension to merge-gate, not maintained by the exasol-toolbox.

name: Merge-Gate Extension

on:
  workflow_call:

jobs:

  performance-checks:
    name: Performance
    uses: ./.github/workflows/performance-checks.yml
    permissions:
      contents: read

  approve-notebook-tests:
    name: Run Jupyter Notebook Tests?
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    environment: approve-notebook-tests
    steps:
      - name: Detect Running Notebook Tests
        run: true

  run-notebook-tests:
    name: Notebook Tests
    needs:
      - approve-notebook-tests
    uses: ./.github/workflows/tests-notebooks.yml
    with:
      selector: generic
    secrets: inherit
    permissions:
      contents: read

  approve-gpu-notebook-tests:
    name: Run Jupyter GPU Notebook Tests?
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    environment: approve-gpu-notebook-tests
    steps:
      - name: Detect Running GPU Notebook Tests
        run: true

  run-gpu-notebook-tests:
    name: Notebook Tests GPU
    needs:
      - approve-notebook-tests
      - approve-gpu-notebook-tests
    uses: ./.github/workflows/tests-notebooks.yml
    with:
      selector: gpu
    secrets: inherit
    permissions:
      contents: read
