name: Merge-Gate

on:
  workflow_call:

jobs:
  run-fast-checks:
    name: Fast Checks
    uses: ./.github/workflows/checks.yml
    permissions:
      contents: read

  approve-run-slow-tests:
    name: Approve Running Slow Tests?
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    # Even though the environment "manual-approval" will be created automatically,
    # it still needs to be configured to require interactive review.
    # See project settings on GitHub (Settings / Environments / manual-approval).
    environment: manual-approval
    steps:
      - name: Tests
        run: echo "Slow tests approved"

  run-slow-checks:
    name: Slow Checks
    needs:
      - approve-run-slow-tests
    uses: ./.github/workflows/slow-checks.yml
    secrets: inherit
    permissions:
      contents: read

  optional-slow-checks:
    name: Optional Slow
    needs:
      - approve-run-slow-tests
    uses: ./.github/workflows/tests-saas.yml
    secrets: inherit
    permissions:
      contents: read

  performance-checks:
    name: Performance
    uses: ./.github/workflows/performance-checks.yml
    permissions:
      contents: read

  # This job ensures inputs have been executed successfully.
  allow-merge:
    name: Allow Merge
    if: ${{ !cancelled() }}
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    needs:
      - run-fast-checks
      - run-slow-checks
    steps:
      - name: Branch Protection - failure if any ancestor failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: |
          echo '${{ toJSON(needs) }}'
          exit 1
      - name: Approve
        run: echo "Merge Approved"
