name: Slow-Checks

on:
  workflow_call:
    secrets:
      INTEGRATION_TEAM_SAAS_STAGING_HOST:
        required: true
      INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID:
        required: true
      INTEGRATION_TEAM_SAAS_STAGING_PAT:
        required: true
      ZIP_PASSWORD:
        required: true

jobs:

  ordinary-itests:
    name: Ordinary iTests
    uses: ./.github/workflows/tests-ordinary-integration.yml
    permissions:
      contents: read

  large-runner-tests:
    name: Large Runner
    uses: ./.github/workflows/tests-large-runner.yml
    permissions:
      contents: read
    secrets:
      ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}

  gpu-tests:
    name: GPU
    uses: ./.github/workflows/tests-gpu.yml
    permissions:
      contents: read

  ui-tests:
    name: UI
    uses: ./.github/workflows/tests-ui.yml
    permissions:
      contents: read

  optional-slow-checks:
    name: Optional Slow
    uses: ./.github/workflows/tests-saas.yml
    secrets:
      INTEGRATION_TEAM_SAAS_STAGING_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
      INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
      INTEGRATION_TEAM_SAAS_STAGING_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
    permissions:
      contents: read
