name: Slow-Checks

on:
  workflow_call:
    secrets:
      INTEGRATION_TEAM_SAAS_STAGING_HOST:
        required: true
      INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID:
        required: true
      INTEGRATION_TEAM_SAAS_STAGING_PAT:
        required: true
      ZIP_PASSWORD:
        required: true

jobs:
  build-matrix:
    name: Build Matrix
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["minimum_python_version"]'
    permissions:
      contents: read

  ordinary-itests:
    name: Ordinary iTests
    needs:
      - build-matrix
    uses: ./.github/workflows/tests-ordinary-integration.yml
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    with:
      python_version: ${{ matrix.minimum_python_version }}

  large-runner-tests:
    name: Large Runner
    needs:
      - build-matrix
    uses: ./.github/workflows/tests-large-runner.yml
    permissions:
      contents: read
    secrets:
      ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    with:
      python_version: ${{ matrix.minimum_python_version }}

  gpu-tests:
    name: GPU
    needs:
      - build-matrix
    uses: ./.github/workflows/tests-gpu.yml
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    with:
      python_version: ${{ matrix.minimum_python_version }}

  ui-tests:
    name: UI
    needs:
      - build-matrix
    uses: ./.github/workflows/tests-ui.yml
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    with:
      python_version: ${{ matrix.minimum_python_version }}

  optional-slow-checks:
    name: Optional Slow
    uses: ./.github/workflows/tests-saas.yml
    needs:
      - build-matrix
    secrets:
      INTEGRATION_TEAM_SAAS_STAGING_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
      INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
      INTEGRATION_TEAM_SAAS_STAGING_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    with:
      python_version: ${{ matrix.minimum_python_version }}
