name: Notebook Tests

on:
  workflow_call:
    inputs:
      status-filter:
        description: 'Only nb tests with the given status will be executed (stable or unstable).'
        required: true
        type: string
      test-classification:
        description: 'Test classification: normal, large or gpu'
        required: true
        type: string

jobs:

  fetch-notebook-tests:
    runs-on: ubuntu-24.04
    name: Fetching ${{ inputs.status-filter }} ${{ inputs.test-classification }} notebook tests
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          poetry-version: "2.3.0"

      - id: set-tests
        run: |
          TESTS=$(poetry run -- nox -s get-notebook-tests -- \
            --test-status ${{ inputs.status-filter }} \
            --test-classification ${{ inputs.test-classification }})
          echo "tests=$TESTS" >> "$GITHUB_OUTPUT"

      - id: set-runner
        run: |
          RUNNER=$(poetry run -- nox -s get-notebook-runner -- \
            --test-status ${{ inputs.status-filter }} \
            --test-classification ${{ inputs.test-classification }})
          echo "runner=$RUNNER" >> "$GITHUB_OUTPUT"

      - id: set-pytest-params
        run: |
          PARAMS=$(poetry run -- nox -s get-notebook-pytest-params -- \
            --test-status ${{ inputs.status-filter }} \
            --test-classification ${{ inputs.test-classification }})
          echo "pytest_params=$PARAMS" >> "$GITHUB_OUTPUT"

    outputs:
      tests: ${{ steps.set-tests.outputs.tests }}
      runner: ${{ steps.set-runner.outputs.runner }}
      pytest_params: ${{ steps.set-pytest-params.outputs.pytest_params }}


  notebook-tests:
    name: ${{ matrix.nb_test.name }} (${{ matrix.nb_test.test_backend }})
    needs: fetch-notebook-tests
    runs-on: ${{ needs.fetch-notebook-tests.outputs.runner }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        nb_test: ${{ fromJson(needs.fetch-notebook-tests.outputs.tests).tests }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          large-packages: false
          haskell: true

      - name: Free disk space by removing large directories
        run: |
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          poetry-version: "2.3.0"

      - name: Install All Optional Dependencies (aka. "extras")
        run: poetry install --all-extras

      - name: Allow unprivileged user namespaces
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Run Notebook Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
          NBTEST_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          NBTEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          NBTEST_AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          poetry run -- pytest -rA --setup-show \
            --backend ${{ matrix.nb_test.test_backend }} \
            ${{ needs.fetch-notebook-tests.outputs.pytest_params }} \
            test/notebooks/${{ matrix.nb_test.test_file }}