name: Notebook Tests

on:
  workflow_call:

jobs:

  notebook-tests:
    name: Notebook Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - file: nbtest_first_steps.py
          - file: nbtest_sklearn.py
          - file: nbtest_pyexasol.py
          - file: nbtest_jupysql.py
          - file: nbtest_ibis.py
          - file: nbtest_script_languages_container.py
          - file: nbtest_itde.py
          - file: nbtest_useful_urls.py
          - file: nbtest_cloud.py

    steps:

      - name: SCM Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          large-packages: false
          haskell: true

      - name: Free disk space by removing large directories
        run: |
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          poetry-version: "2.3.0"

      - name: Install All Optional Dependencies (aka. "extras")
        run: poetry install --all-extras

      - name: Allow unprivileged user namespaces
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Pytest
        run: |
          poetry run -- pytest -rA --setup-show \
            -c test/notebooks/pytest.ini \
            --backend onprem \
            --itde-nameserver 8.8.8.8 \
            test/notebooks/${{ matrix.file }}
