name: Notebook Tests

on:
  workflow_call:
    inputs:
      selector:
        description: Selector which tests to include, e.g. notebooks-generic
        required: true
        type: string

jobs:

  fetch-notebook-tests:
    runs-on: ubuntu-24.04
    name: Build Matrix ${{ inputs.selector }}
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v8
        with:
          poetry-version: "2.3.0"

      - id: matrix
        run: |
          JOBS=$(poetry run -- nox -s get-notebook-tests -- ${{ inputs.selector }})
          echo "jobs=$JOBS" >> "$GITHUB_OUTPUT"

    outputs:
      jobs: ${{ steps.matrix.outputs.jobs }}

  notebook-tests:
    name: >
      ${{ matrix.job.name }} (${{ matrix.job.backend
      }}${{ case(matrix.job.require_success, '', ', optional') }})
    needs: fetch-notebook-tests
    runs-on: ${{ matrix.job.runner }}
    permissions:
      contents: read
    continue-on-error: ${{ ! matrix.job.require_success }}
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJson(needs.fetch-notebook-tests.outputs.jobs) }}

    steps:
    # experimental
    #
    #  - name: SCM Checkout
    #    uses: actions/checkout@v6
    #    with:
    #      fetch-depth: 0
    #
    #  - name: Free disk space
    #    uses: jlumbroso/free-disk-space@main
    #    with:
    #      tool-cache: true
    #      large-packages: false
    #      haskell: true
    #
    #  - name: Free disk space by removing large directories
    #    run: |
    #      sudo rm -rf /usr/local/graalvm/
    #      sudo rm -rf /usr/local/share/powershell
    #      sudo rm -rf /usr/local/share/chromium
    #      sudo rm -rf /usr/local/lib/node_modules
    #
    #  - name: Setup Python & Poetry Environment
    #    uses: exasol/python-toolbox/.github/actions/python-environment@v8
    #    with:
    #      poetry-version: "2.3.0"
    #
    #  - name: Install All Optional Dependencies (aka. "extras")
    #    run: poetry install --all-extras
    #
    #  - name: Allow unprivileged user namespaces
    #    run: |
    #      sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - id: test
        name: Run Pytest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
          NBTEST_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          NBTEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NBTEST_AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          NBTEST_USE_GPU: ${{ case(inputs.selector == 'gpu', 'true', 'false') }}
        run: |
          # experimental
          echo poetry run -- pytest -rA --setup-show \
            --backend=${{ matrix.job.backend }} \
            ${{ matrix.job.pytest_params }} \
            test/notebooks/${{ matrix.job.file }}

      - name: Save Result
        if: always()
        run: |
          mkdir -p results
          jq -n '{
            file: "${{ matrix.job.file }}",
            require_success: ${{ matrix.job.require_success }},
            backend: "${{ matrix.job.backend }}",
            runner: "${{ matrix.job.runner }}",
            outcome: "${{ steps.test.outcome }}"
          }' > results/${{ matrix.job.file }}.json

      # experimental
      - name: Save Result
        if: always()
        run: |
          jq -n '{
            file: "${{ matrix.job.file }}",
            require_success: ${{ matrix.job.require_success }},
            backend: "${{ matrix.job.backend }}",
            runner: "${{ matrix.job.runner }}",
            outcome: "${{ case( matrix.job.require_success, 'success', 'failure' ) }}"
          }' > results/${{ matrix.job.file }}.json

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-result-${{ matrix.job.file }}
          path: results/${{ matrix.job.file }}.json

  evaluate-tests:
    name: Evaluate Test Results
    runs-on: ubuntu-24.04
    if: always()
    needs: notebook-tests
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v8
        with:
          poetry-version: "2.3.0"

      - name: Download Test Results
        uses: actions/download-artifact@v8
        with:
          pattern: test-result-*
          path: results
          merge-multiple: true

      - name: Verify Success of Mandatory Tests
        run: poetry run -- nox -s test:notebooks:evaluate-results -- results/*.json
