name: Sagemaker Notebook Tests

on:
  workflow_call:

jobs:

  notebook-sagemaker-tests:
    name: Sagemaker Notebook Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:

      - name: SCM Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          large-packages: false
          haskell: true

      - name: Free disk space by removing large directories
        run: |
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          poetry-version: "2.3.0"

      - name: Install All Optional Dependencies (aka. "extras")
        run: poetry install --all-extras

      - name: Allow unprivileged user namespaces
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Pytest
        env:
          NBTEST_AWS_DEFAULT_REGION: ${{ secrets.NBTEST_AWS_DEFAULT_REGION }}
          NBTEST_AWS_ACCESS_KEY_ID: ${{ secrets.NBTEST_AWS_ACCESS_KEY_ID }}
          NBTEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.NBTEST_AWS_SECRET_ACCESS_KEY }}
        run: |
          poetry run -- pytest -rA --setup-show \
            -c test/notebooks/pytest.ini \
            --backend onprem \
            --itde-nameserver 8.8.8.8 \
            test/notebooks/nbtest_sagemaker.py
